dataset:
  N: 100
  T: 10
  c_sizes:
  - 20
  - 20
  - 20
  decay_prop: 0.2
  loader_name: TFTSampler
  max_n: 60
  n_communities: 3
  n_workers: 6
  name: 3_comm_decay
  p_ext: 0.01
  p_int: 0.8
exp_dir: experiment_files/
exp_name: AGE_3_comm_decay_2024-Sep-12-06-58-20_5228
experiment:
  gpus:
  - 0
  test:
    batch_size: 32
    best_val_epoch: 5
    graph_dir: experiment_files/AGE_3_comm_decay_2024-Sep-12-06-58-20_5228
    loader: GNNTestSampler
  train:
    batch_size: 16
    clip_grad: 3
    cycle_len: 75
    display_iters: 10
    epochs: 10000
    es_improvement_len: 8000
    label_smoothing: 0.0
    lr: 0.001
    lr_decay: 0.3
    milestones:
    - 250
    - 750
    num_workers: 4
    optimizer: Adam
    prev_edge_smoothing: 0.1
    shuffle_data: true
    snapshot_epochs: 50
    use_writer: false
    weight_decay: 0.0002
  validation:
    batch_size: 10000
    es_buffer: 100
    es_patience: 20
    val_epochs: 5
    val_p: 0.2
model:
  decoder:
    dim_feedforward: 1024
    dropout: 0.2
    num_attn_heads: 2
    num_layers: 6
  encoder:
    dim_feedforward: 1024
    dropout: 0.2
    hidden_size: 128
    input_size: 60
    num_attn_heads: 8
    num_layers: 6
  hidden_size: 128
  name: AGE
model_save_dir: experiment_files/AGE_3_comm_decay_2024-Sep-12-06-58-20_5228/models
run_id: '5228'
save_dir: experiment_files/AGE_3_comm_decay_2024-Sep-12-06-58-20_5228
seed: 123
